version: '3.9'

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: directedgraph
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - my-db:/var/lib/mysql
    profiles:
      - dev
      - test
      
  directedgraph:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    restart: always
    depends_on:
      - db
    environment:
      DB_USER: user
      DB_PASSWORD: password
      DB_HOST: db
      DB_NAME: directedgraph
    ports:
      - 8080:8080
    profiles:
      - dev
      
  directedgraph_test:
    build:
      context: ../
      dockerfile: docker/Dockerfile.test
    restart: "no"
    depends_on:
      - db
    environment:
      DB_USER: user
      DB_PASSWORD: password
      DB_HOST: db
      DB_NAME: directedgraph_test
      SERVER_PORT: 8081
    ports:
      - 8081:8081
    profiles:
      - test
      
volumes:
  my-db: